@url = http://localhost:2800

### GET 
GET {{url}}/

### GET PROFILE
GET {{url}}/profile/633550f8e91ed4ca398397b0
### CREATE
POST {{url}}/create
Content-Type: application/json

{
    "name":"unai",
    "age":29,
    "job":"ever",
    "bio":"for"
}

### UPDATE
PUT {{url}}/update/633490461b2ac67275caaec4
Content-Type: application/json

{
    "age": 30
}

### DELETE
DELETE {{url}}/delete/633550f8e91ed4ca398397b0

